/**
 * Earthquake Monitor API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EarthquakeFilter } from './earthquake-filter';
import { PaginationParams } from './pagination-params';


export interface BodyListEarthquakesApiV1EarthquakesListGet { 
    filters?: EarthquakeFilter;
    pagination?: PaginationParams;
}

