/**
 * Earthquake Monitor API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Schema for data synchronization operation responses
 */
export interface DataResponse { 
    /**
     * Whether the synchronization was successful
     */
    success: boolean;
    /**
     * Operation status message
     */
    message: string;
    /**
     * Number of records fetched from USGS API
     */
    records_processed: number;
    /**
     * Number of new records saved to database
     */
    records_inserted: number;
    /**
     * Operation start time
     */
    start_time: string;
    /**
     * Operation end time
     */
    end_time: string;
    /**
     * Operation duration in seconds
     */
    duration_seconds: number;
}

