/**
 * Earthquake Monitor API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Schema for manual data synchronization requests
 */
export interface DataRequest { 
    /**
     * Cannot be a future date
     */
    since_datetime?: string;
}

