/**
 * Earthquake Monitor API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Schema for earthquake API responses
 */
export interface EarthquakeResponse { 
    /**
     * Earthquake occurrence time (UTC)
     */
    time: string;
    /**
     * Latitude coordinate (-90 to 90)
     */
    latitude: number;
    /**
     * Longitude coordinate (-180 to 180)
     */
    longitude: number;
    depth?: number | null;
    magnitude?: number | null;
    magnitude_type?: string | null;
    place?: string | null;
    /**
     * USGS unique identifier
     */
    id: string;
    /**
     * Record insertion timestamp
     */
    created_at: string;
}

