/**
 * Earthquake Monitor API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EarthquakeFilter } from './earthquake-filter';
import { PaginationParams } from './pagination-params';


/**
 * Schema for earthquake list request with filters and pagination.  This wrapper schema ensures proper OpenAPI schema generation for TypeScript client code generation. By combining filters and pagination into a single request body, we maintain a single source of truth while enabling automatic interface generation in the frontend.
 */
export interface ListEarthquakesRequest { 
    /**
     * Filter criteria for earthquake records
     */
    filters?: EarthquakeFilter;
    /**
     * Pagination parameters for result set
     */
    pagination?: PaginationParams;
}

