"""optimize_indexes_time_and_place

Revision ID: 2ff82821ecda
Revises: 6c8477ece3b3
Create Date: 2025-11-23 20:25:58.024826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ff82821ecda'
down_revision: Union[str, Sequence[str], None] = '6c8477ece3b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_earthquakes_location'), table_name='earthquakes')
    op.drop_index(op.f('idx_earthquakes_magnitude'), table_name='earthquakes')
    op.create_index('idx_earthquakes_place_gin', 'earthquakes', ['place'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_earthquakes_place_gin', table_name='earthquakes', postgresql_using='gin')
    op.create_index(op.f('idx_earthquakes_magnitude'), 'earthquakes', ['magnitude'], unique=False)
    op.create_index(op.f('idx_earthquakes_location'), 'earthquakes', ['latitude', 'longitude'], unique=False)
    # ### end Alembic commands ###
