"""Create earthquake table

Revision ID: 6c8477ece3b3
Revises: 
Create Date: 2025-11-18 21:53:41.747389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c8477ece3b3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('earthquakes',
    sa.Column('id', sa.String(length=50), nullable=False, comment='USGS unique identifier'),
    sa.Column('time', sa.TIMESTAMP(), nullable=False, comment='Earthquake occurrence time (UTC)'),
    sa.Column('latitude', sa.DECIMAL(precision=9, scale=6), nullable=False, comment='Latitude coordinate (-90 to 90)'),
    sa.Column('longitude', sa.DECIMAL(precision=9, scale=6), nullable=False, comment='Longitude coordinate (-180 to 180)'),
    sa.Column('depth', sa.DECIMAL(precision=6, scale=2), nullable=True, comment='Depth in kilometers'),
    sa.Column('magnitude', sa.DECIMAL(precision=3, scale=2), nullable=True, comment='Earthquake magnitude'),
    sa.Column('magnitude_type', sa.String(length=10), nullable=True, comment='Magnitude type (mb, ml, mw, etc)'),
    sa.Column('place', sa.Text(), nullable=True, comment='Location description'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Record insertion timestamp'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_earthquakes_location', 'earthquakes', ['latitude', 'longitude'], unique=False)
    op.create_index('idx_earthquakes_magnitude', 'earthquakes', ['magnitude'], unique=False)
    op.create_index('idx_earthquakes_time', 'earthquakes', ['time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_earthquakes_time', table_name='earthquakes')
    op.drop_index('idx_earthquakes_magnitude', table_name='earthquakes')
    op.drop_index('idx_earthquakes_location', table_name='earthquakes')
    op.drop_table('earthquakes')
    # ### end Alembic commands ###
